language: node_js
node_js:
  - 12
services: mongodb
after_success:
  - npm install serverless -g
  - serverless config credentials --provider aws --key ${AWS_ACCESS_KEY_ID} --secret ${AWS_SECRET_ACCESS_KEY}
  - serverless deploy
