service: deardiary
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-southeast-1
  profile: 'serverless'
  memorySize: 128
functions:
  app:
    handler: app/app.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
